### ISSUE TITLE
Using data derived from tool to cut the data collected in the cutting insert data error < DataTypeNotMatchException: (code = 0, message= the data fields number is not match with schema.)> ID becomes mandatory

### ISSUE THREAD

**Issue by gll963** [zilliztech/milvus-backup#111]
### Current Behavior

Utility derived data reduction data collection in the reduction of the insert data error < DataTypeNotMatchException: (code=0, message=The data fields number is not match with schema.)> ID becomes mandatory

**Comment by zhuwenxing** [comment]
/assign @gll963 
Please offer more information in the issue template, thanks!

**Comment by gll963** [comment]
1   ./milvus-backup create -n my_123
2   ./milvus-backup restore -n my_123
3   Load the imported collection index
4   Insert vector data into the collection imported by the backup
5   When the program id field of the insert vector is empty, the insert error is missing the id field，error < DataTypeNotMatchException: (code=0, message=The data fields number is not match with schema.)> ID
6   Collection id field auto id before backup =true

**Comment by zhuwenxing** [comment]
It should be fixed by https://github.com/zilliztech/milvus-backup/pull/112.
Please try the latest release https://github.com/zilliztech/milvus-backup/releases/tag/v0.2.1
