### ISSUE TITLE
[Bug]: Restored collection much larger than backup, restores data multiple times

### ISSUE THREAD

**Issue by akevdmeer** [zilliztech/milvus-backup#118]
### Current Behavior

When I restore a large collection (400GB), which first requires increasing all relevant timeouts, I find that the restore keeps on going and the collection being restored grows larger than the original.

Looking at the S3 access logs, I find that it starts to retrieve the same objects again after some five hours running time.

It seems that the issue is with listing the keys based on a prefix with groupId. For groupId 1 it lists all prefixes for all groupIds that start with the digit 1, so also 10, 11, etc. It's when milvus-backup reaches groupId 10 that it starts to 'restore' from objects from which it has already restored.

### Expected Behavior

Don't restore data more than once.

### Steps To Reproduce

Restore a collection that has more than 9 segment groups.

### Environment

Milvus 2.2.4, milvus-backup 0.2.1.

**Comment by zhuwenxing** [comment]
Thanks for your feedback. Can you please upload the log of milvus-backup? The log is located in the path that is configured in the `configs/backup.yaml` https://github.com/zilliztech/milvus-backup/blob/5c41347ba56f54dc9273195d10ace278c6a66444/configs/backup.yaml#L6

**Comment by akevdmeer** [comment]
At a guess, I'd say it's the lack of trailing slash [here](https://github.com/zilliztech/milvus-backup/blob/main/core/backup_context.go#L1480-L1481) in getBackupPartitionPathsWithGroupID(), compare with getBackupPartitionPathsWithGroupID(). I can try that and provide debug logs next week.

**Comment by zhuwenxing** [comment]
/assign @wayblink 
PTAL

**Comment by wayblink** [comment]
@akevdmeer Thanks a lot for reporting such an important issue. I think it may be a bug. I will verify and fix it.

**Comment by wayblink** [comment]
> @akevdmeer Thanks a lot for reporting such an important issue. I think it may be a bug. I will verify and fix it.

fix in #121
