### ISSUE TITLE
[Bug]: use Dockerfile build failure

### ISSUE THREAD

**Issue by qilaijun101** [zilliztech/milvus-backup#124]
### Current Behavior

use Dockerfile build failure

### Steps To Reproduce

```markdown
1.docker file 

From  golang:1.18 AS builder

ENV CGO_ENABLED=0
WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o /app/milvus-backup

From alpine:3.17
WORKDIR /app
COPY --from=builder /app/milvus-backup .
COPY --from=builder /app/configs ./configs
EXPOSE 8080
ENTRYPOINT ["milvus-backup", "server"]
```

### Anything else?

#DOME:git checkout -f 287d0185e3bd532406d5c55ef924356b4f93a015
HEAD is now at 287d018 hot fix
#DOME:git submodule init
#DOME:git submodule update
#DOME:cd /code//
#DOME:docker build --rm --pull -f /code//Dockerfile -t private-registry.sohucs.com/milvus-backup/milvus-backup:master_txy_287d018 /code//
Sending build context to Docker daemon  71.13MB
Step 1/12 : From  golang:1.18 AS builder
1.18: Pulling from library/golang
bbeef03cda1f: Pulling fs layer
f049f75f014e: Pulling fs layer
56261d0e6b05: Pulling fs layer
9bd150679dbd: Pulling fs layer
bfcb68b5bd10: Pulling fs layer
06d0c5d18ef4: Pulling fs layer
cc7973a07a5b: Pulling fs layer
9bd150679dbd: Waiting
bfcb68b5bd10: Waiting
cc7973a07a5b: Waiting
f049f75f014e: Verifying Checksum
f049f75f014e: Download complete
56261d0e6b05: Verifying Checksum
56261d0e6b05: Download complete
bbeef03cda1f: Verifying Checksum
bbeef03cda1f: Download complete
bbeef03cda1f: Pull complete
f049f75f014e: Pull complete
56261d0e6b05: Pull complete
9bd150679dbd: Verifying Checksum
9bd150679dbd: Download complete
cc7973a07a5b: Verifying Checksum
cc7973a07a5b: Download complete
bfcb68b5bd10: Verifying Checksum
bfcb68b5bd10: Download complete
9bd150679dbd: Pull complete
bfcb68b5bd10: Pull complete
06d0c5d18ef4: Verifying Checksum
06d0c5d18ef4: Download complete
06d0c5d18ef4: Pull complete
cc7973a07a5b: Pull complete
Digest: sha256:50c889275d26f816b5314fc99f55425fa76b18fcaf16af255f5d57f09e1f48da
Status: Downloaded newer image for golang:1.18
 ---> c37a56a6d654
Step 2/12 : ENV CGO_ENABLED=0
 ---> Running in fa3d0db82704
Removing intermediate container fa3d0db82704
 ---> 4233f1e5a140
Step 3/12 : WORKDIR /app
 ---> Running in 012825a8994c
Removing intermediate container 012825a8994c
 ---> fbc0df0d07f8
Step 4/12 : COPY . .
 ---> 859d26d83120
Step 5/12 : RUN go mod tidy
 ---> Running in e97ec92c78de
go: downloading github.com/swaggo/swag v1.8.10
go: downloading github.com/spf13/cobra v1.5.0
go: downloading golang.org/x/sync v0.0.0-20220722155255-886fb9371eb4
go: downloading google.golang.org/grpc v1.48.0
go: downloading go.uber.org/atomic v1.10.0
go: downloading github.com/stretchr/testify v1.8.1
go: downloading github.com/golang/protobuf v1.5.2
go: downloading go.etcd.io/etcd/client/v3 v3.5.0
go: downloading github.com/google/btree v1.0.1
go: downloading golang.org/x/exp v0.0.0-20200224162631-6cc2880d07d6
go: downloading github.com/spf13/cast v1.3.1
go: downloading go.uber.org/zap v1.17.0
go: downloading github.com/spf13/viper v1.8.1
go: downloading github.com/minio/minio-go/v7 v7.0.17
go: downloading gopkg.in/natefinch/lumberjack.v2 v2.0.0
go: downloading github.com/uber/jaeger-client-go v2.25.0+incompatible
go: downloading github.com/sony/sonyflake v1.1.0
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/lingdor/stackerror v0.0.0-20191119040541-976d8885ed76
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/gin-gonic/gin v1.8.1
go: downloading github.com/blang/semver/v4 v4.0.0
go: downloading github.com/wayblink/milvus-sdk-go/v2 v2.2.16
go: downloading github.com/swaggo/gin-swagger v1.5.3
go: downloading github.com/swaggo/files v1.0.0
go: downloading golang.org/x/oauth2 v0.0.0-20210402161424-2e8d93401602
go: downloading github.com/pkg/errors v0.9.1
github.com/zilliztech/milvus-backup/cmd imports
	github.com/spf13/cobra: github.com/spf13/cobra@v1.5.0: Get "https://proxy.golang.org/github.com/spf13/cobra/@v/v1.5.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core imports
	github.com/gin-gonic/gin: github.com/gin-gonic/gin@v1.8.1: Get "https://proxy.golang.org/github.com/gin-gonic/gin/@v/v1.8.1.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core imports
	github.com/milvus-io/milvus-sdk-go/v2/client: github.com/wayblink/milvus-sdk-go/v2@v2.2.16: Get "https://proxy.golang.org/github.com/wayblink/milvus-sdk-go/v2/@v/v2.2.16.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core imports
	github.com/milvus-io/milvus-sdk-go/v2/entity: github.com/wayblink/milvus-sdk-go/v2@v2.2.16: Get "https://proxy.golang.org/github.com/wayblink/milvus-sdk-go/v2/@v/v2.2.16.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core imports
	github.com/swaggo/files: github.com/swaggo/files@v1.0.0: Get "https://proxy.golang.org/github.com/swaggo/files/@v/v1.0.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core imports
	github.com/swaggo/gin-swagger: github.com/swaggo/gin-swagger@v1.5.3: Get "https://proxy.golang.org/github.com/swaggo/gin-swagger/@v/v1.5.3.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core imports
	go.uber.org/zap: go.uber.org/zap@v1.17.0: Get "https://proxy.golang.org/go.uber.org/zap/@v/v1.17.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/paramtable imports
	github.com/spf13/cast: github.com/spf13/cast@v1.3.1: Get "https://proxy.golang.org/github.com/spf13/cast/@v/v1.3.1.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/paramtable imports
	github.com/spf13/viper: github.com/spf13/viper@v1.8.1: Get "https://proxy.golang.org/github.com/spf13/viper/@v/v1.8.1.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/proto/backuppb imports
	github.com/golang/protobuf/proto: github.com/golang/protobuf@v1.5.2: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.2.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/proto/backuppb imports
	google.golang.org/grpc: google.golang.org/grpc@v1.48.0: Get "https://proxy.golang.org/google.golang.org/grpc/@v/v1.48.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/proto/backuppb imports
	google.golang.org/grpc/codes: google.golang.org/grpc@v1.48.0: Get "https://proxy.golang.org/google.golang.org/grpc/@v/v1.48.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/proto/backuppb imports
	google.golang.org/grpc/status: google.golang.org/grpc@v1.48.0: Get "https://proxy.golang.org/google.golang.org/grpc/@v/v1.48.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/storage imports
	github.com/minio/minio-go/v7: github.com/minio/minio-go/v7@v7.0.17: Get "https://proxy.golang.org/github.com/minio/minio-go/v7/@v/v7.0.17.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/storage imports
	github.com/minio/minio-go/v7/pkg/credentials: github.com/minio/minio-go/v7@v7.0.17: Get "https://proxy.golang.org/github.com/minio/minio-go/v7/@v/v7.0.17.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/storage imports
	golang.org/x/exp/mmap: golang.org/x/exp@v0.0.0-20200224162631-6cc2880d07d6: Get "https://proxy.golang.org/golang.org/x/exp/@v/v0.0.0-20200224162631-6cc2880d07d6.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/storage/gcp imports
	github.com/pkg/errors: github.com/pkg/errors@v0.9.1: Get "https://proxy.golang.org/github.com/pkg/errors/@v/v0.9.1.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/storage/gcp imports
	go.uber.org/atomic: go.uber.org/atomic@v1.10.0: Get "https://proxy.golang.org/go.uber.org/atomic/@v/v1.10.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/storage/gcp imports
	golang.org/x/oauth2: golang.org/x/oauth2@v0.0.0-20210402161424-2e8d93401602: Get "https://proxy.golang.org/golang.org/x/oauth2/@v/v0.0.0-20210402161424-2e8d93401602.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/storage/gcp imports
	golang.org/x/oauth2/google: golang.org/x/oauth2@v0.0.0-20210402161424-2e8d93401602: Get "https://proxy.golang.org/golang.org/x/oauth2/@v/v0.0.0-20210402161424-2e8d93401602.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/utils imports
	github.com/blang/semver/v4: github.com/blang/semver/v4@v4.0.0: Get "https://proxy.golang.org/github.com/blang/semver/v4/@v/v4.0.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/utils imports
	github.com/google/uuid: github.com/google/uuid@v1.1.2: Get "https://proxy.golang.org/github.com/google/uuid/@v/v1.1.2.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core/utils imports
	github.com/sony/sonyflake: github.com/sony/sonyflake@v1.1.0: Get "https://proxy.golang.org/github.com/sony/sonyflake/@v/v1.1.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/docs imports
	github.com/swaggo/swag: github.com/swaggo/swag@v1.8.10: Get "https://proxy.golang.org/github.com/swaggo/swag/@v/v1.8.10.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/common imports
	golang.org/x/sync/errgroup: golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4: Get "https://proxy.golang.org/golang.org/x/sync/@v/v0.0.0-20220722155255-886fb9371eb4.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/common imports
	golang.org/x/time/rate: golang.org/x/time@v0.0.0-20191024005414-555d28b269f0: Get "https://proxy.golang.org/golang.org/x/time/@v/v0.0.0-20191024005414-555d28b269f0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/kv imports
	go.etcd.io/etcd/client/v3: go.etcd.io/etcd/client/v3@v3.5.0: Get "https://proxy.golang.org/go.etcd.io/etcd/client/v3/@v/v3.5.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/kv/mem imports
	github.com/google/btree: github.com/google/btree@v1.0.1: Get "https://proxy.golang.org/github.com/google/btree/@v/v1.0.1.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/log imports
	github.com/uber/jaeger-client-go/utils: github.com/uber/jaeger-client-go@v2.25.0+incompatible: Get "https://proxy.golang.org/github.com/uber/jaeger-client-go/@v/v2.25.0+incompatible.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/log imports
	go.uber.org/zap/buffer: go.uber.org/zap@v1.17.0: Get "https://proxy.golang.org/go.uber.org/zap/@v/v1.17.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/log imports
	go.uber.org/zap/zapcore: go.uber.org/zap@v1.17.0: Get "https://proxy.golang.org/go.uber.org/zap/@v/v1.17.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/log imports
	go.uber.org/zap/zaptest: go.uber.org/zap@v1.17.0: Get "https://proxy.golang.org/go.uber.org/zap/@v/v1.17.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/log imports
	gopkg.in/natefinch/lumberjack.v2: gopkg.in/natefinch/lumberjack.v2@v2.0.0: Get "https://proxy.golang.org/gopkg.in/natefinch/lumberjack.v2/@v/v2.0.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/util/grpcclient imports
	google.golang.org/grpc/backoff: google.golang.org/grpc@v1.48.0: Get "https://proxy.golang.org/google.golang.org/grpc/@v/v1.48.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/util/grpcclient imports
	google.golang.org/grpc/keepalive: google.golang.org/grpc@v1.48.0: Get "https://proxy.golang.org/google.golang.org/grpc/@v/v1.48.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/util/logutil imports
	google.golang.org/grpc/grpclog: google.golang.org/grpc@v1.48.0: Get "https://proxy.golang.org/google.golang.org/grpc/@v/v1.48.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core tested by
	github.com/zilliztech/milvus-backup/core.test imports
	github.com/stretchr/testify/assert: github.com/stretchr/testify@v1.8.1: Get "https://proxy.golang.org/github.com/stretchr/testify/@v/v1.8.1.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/core tested by
	github.com/zilliztech/milvus-backup/core.test imports
	github.com/stretchr/testify/require: github.com/stretchr/testify@v1.8.1: Get "https://proxy.golang.org/github.com/stretchr/testify/@v/v1.8.1.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/zilliztech/milvus-backup/internal/util/retry tested by
	github.com/zilliztech/milvus-backup/internal/util/retry.test imports
	github.com/lingdor/stackerror: github.com/lingdor/stackerror@v0.0.0-20191119040541-976d8885ed76: Get "https://proxy.golang.org/github.com/lingdor/stackerror/@v/v0.0.0-20191119040541-976d8885ed76.zip": dial tcp 142.251.42.241:443: i/o timeout
The command '/bin/sh -c go mod tidy' returned a non-zero code: 1

**Comment by zhuwenxing** [comment]
From the log, the most error is network timeout for fetching the go module. Please check whether your network can access them, or just add go proxy in docker file

**Comment by qilaijun101** [comment]
> From the log, the most error is network timeout for fetching the go module. Please check whether your network can access them, or just add go proxy in docker file

ok. I add ENV GOPROXY="https://goproxy.io" and try again
