### ISSUE TITLE
[Bug]The docker container can not run with the default dockerfile

### ISSUE THREAD

**Issue by qilaijun101** [zilliztech/milvus-backup#125]
### Current Behavior

![image](https://user-images.githubusercontent.com/14890813/234790454-909f18a9-8eaa-4f23-aa8f-aecce707d56a.png)

![image](https://user-images.githubusercontent.com/14890813/234790561-0e16b38f-4881-494e-b420-4f7796c5003e.png)

### Expected Behavior

1. modify the backup.yaml file 
2.go build success with DockerFile 
3.docker run failed 

### Steps To Reproduce

```markdown
1.go build success with DockerFile 

DockerFile

From  golang:1.18 AS builder

ENV GOPROXY="https://goproxy.io"
ENV CGO_ENABLED=0
WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o /app/milvus-backup

From alpine:3.17
WORKDIR /app
COPY --from=builder /app/milvus-backup .
COPY --from=builder /app/configs ./configs
EXPOSE 8080
ENTRYPOINT ["milvus-backup", "server"]


2.and the backup.yaml 

# Configures the system log output.
log:
  level: info # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true
  file:
    rootPath: "logs/backup.log"

http:
  simpleResponse: true

# milvus proxy address, compatible to milvus.yaml
milvus:
  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
  tlsMode: 0
  user: "root"
  password: "Milvus"

# Related configuration of minio, which is responsible for data persistence for Milvus.

  bucketName: "milvus-bucket" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
  rootPath: "/export/milvus-bucket/file" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance

  backupBucketName: "milvus-bucket" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
  backupRootPath: "/export/backup/file" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath

backup:
  maxSegmentGroupSize: 2G
```

### Environment

```markdown
K8s
```

**Comment by qilaijun101** [comment]
kubectl  describe pod milvus-backup-f5f4ff5c7-hczjq   -n ns-milvus-prod
Name:         milvus-backup-f5f4ff5c7-hczjq
Namespace:    ns-milvus-prod
Priority:     0
Node:         10.23.243.52/10.23.243.11
Start Time:   Thu, 27 Apr 2023 15:23:41 +0800
Labels:       k8s-app=milvus-backup
              pod-template-hash=f5f4ff5c7
              qcloud-app=milvus-backup
Annotations:  tke.cloud.tencent.com/networks-status:
                [{
                    "name": "tke-route-eni",
                    "interface": "eth0",
                    "ips": [
                        "10.23.241.147"
                    ],
                    "mac": "92:a3:f3:bc:ae:20",
                    "default": true,
                    "dns": {}
                }]
Status:       Running
IP:           10.23.241.147
IPs:
  IP:           10.23.241.147
Controlled By:  ReplicaSet/milvus-backup-f5f4ff5c7
Containers:
  milvus-backup:
    Container ID:   docker://c6a0a1b76adf0e72de2e0b2cad0a38668723c888f2912f3086cefc9383b61e4f
    Image:          cloud-sample.tencentcloudcr.com/ns-milvus-prod/milvus-backup:master_txy_162ba2e
    Image ID:       docker-pullable://cloud-sample.tencentcloudcr.com/ns-milvus-prod/milvus-backup@sha256:27b972385abe297eda8429ac1e25ed8a2fe27e6bae61b41a4da31b596b72c8d0
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "milvus-backup": executable file not found in $PATH: unknown
      Exit Code:    127
      Started:      Thu, 27 Apr 2023 15:34:26 +0800
      Finished:     Thu, 27 Apr 2023 15:34:26 +0800
    Ready:          False
    Restart Count:  7
    Limits:
      cpu:                           2
      memory:                        4Gi
      tke.cloud.tencent.com/eni-ip:  1
    Requests:
      cpu:                           2
      memory:                        1Gi
      tke.cloud.tencent.com/eni-ip:  1
    Environment:                     <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-w9xjj (ro)
Readiness Gates:
  Type                                                 Status
  cloud.tencent.com/load-balancer-backendgroup-ready   True 
Conditions:
  Type                                                 Status
  cloud.tencent.com/load-balancer-backendgroup-ready   True 
  Initialized                                          True 
  Ready                                                False 
  ContainersReady                                      False 
  PodScheduled                                         True 
Volumes:
  default-token-w9xjj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-w9xjj
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                 Age                From               Message
  ----     ------                 ----               ----               -------
  Normal   Scheduled              13m                default-scheduler  Successfully assigned ns-milvus-prod/milvus-backup-f5f4ff5c7-hczjq to 10.23.243.52
  Normal   SuccessfulOccupyENIIP  13m                tke-eni-ipamd      Succeed to occupy ip 10.23.241.147 of eni eni-1swjk5t6 on node 10.23.243.52
  Normal   SuccessfulAssignIP     13m                tke-eni-ipamd      Succeed to assign ip 10.23.241.147 to eni eni-1swjk5t6
  Normal   Pulled                 11m (x5 over 13m)  kubelet            Container image "cloud-sample.tencentcloudcr.com/ns-milvus-prod/milvus-backup:master_txy_162ba2e" already present on machine
  Normal   Created                11m (x5 over 13m)  kubelet            Created container milvus-backup
  Warning  Failed                 11m (x5 over 13m)  kubelet            Error: failed to start container "milvus-backup": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "milvus-backup": executable file not found in $PATH: unknown
  Warning  BackOff                3m (x44 over 12m)  kubelet            Back-off restarting failed container

**Comment by qilaijun101** [comment]
Error: failed to start container "milvus-backup": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "milvus-backup": executable file not found in $PATH: unknown  @yinheli   please help me check it

**Comment by zhuwenxing** [comment]
Thank you for bringing this to our attention. We noticed that your issue contains sensitive information such as accessKeyID and secretAccessKey. We kindly remind you to reset these credentials to ensure the security of your account.

Deploying the Milvus backup server with docker or k8s is still experimental, and we will publish our official docker hub image after testing.
