### ISSUE TITLE
[Bug]: milvus-backup can backup collection but can not restore  in  a cluster

### ISSUE THREAD

**Issue by qilaijun101** [zilliztech/milvus-backup#129]
### Current Behavior

1 backup success but  get  list null 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14890813/235127477-cce9d13a-ac34-4190-8c99-fff9b8bf5f2f.png">

2. get list is null log

![image](https://user-images.githubusercontent.com/14890813/235130702-5b55899d-bdfc-46fa-ba0a-384675f1c8a7.png)

3.
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/14890813/235130860-eef4b658-b313-4497-b7b9-1fcb60653764.png">

![image](https://user-images.githubusercontent.com/14890813/235131904-82015609-b241-4c95-a0b7-12e61b4de925.png)

### Steps To Reproduce

```markdown
1.backup
```

**Comment by zhuwenxing** [comment]
Can you try again with `async` as false?

**Comment by qilaijun101** [comment]
> Can you try again with `async` as false?

I have tried, but  not

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/14890813/235134806-53646a16-bef8-4215-be77-d7f2829d89d4.png">

**Comment by qilaijun101** [comment]
> book_backup

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/14890813/235139685-3d82f6cc-61a4-432a-8df3-2e3a6a2957e7.png">
 

book_backup  also not ok  @zhuwenxing

**Comment by zhuwenxing** [comment]
And make sure your backup.yaml is right.
If you deploy Milvus using helm with the default config, you can set config as this 

```
  accessKeyID: minioadmin # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""
  
  bucketName: "milvus-bucket" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
  rootPath: "file" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance

  backupBucketName: "milvus-buckett" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
  backupRootPath: "backup" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath
```

Do Not Use **Absolute path** in backupRootPath or rootPath

**Comment by zhuwenxing** [comment]
If you can access your minio console, refer to https://min.io/docs/minio/linux/administration/minio-console.html
You can also check it on the website.

![image](https://user-images.githubusercontent.com/12268675/235187901-7d71d112-4195-4b22-b5ec-570783e04051.png)
