### ISSUE TITLE
[Bug]: ./milvus-backup server got exception

### ISSUE THREAD

**Issue by linggong2023** [zilliztech/milvus-backup#140]
### Current Behavior

[core/backup_context.go:74] ["failed to connect to milvus"] [error="this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server"] [errorVerbose="this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).connectInternal\n  | \t/Users/admin/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/collection.go:84\n  | github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).connect\n  | \t/Users/admin/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/collection.go:54\n  | github.com/milvus-io/milvus-sdk-go/v2/client.NewClient\n  | \t/Users/admin/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/client.go:249\n  | github.com/milvus-io/milvus-sdk-go/v2/client.NewGrpcClient\n  | \t/Users/admin/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.2.20/client/client.go:261\n  | github.com/zilliztech/milvus-backup/core.CreateMilvusClient\n  | \t/Users/admin/code/milvus-backup/core/backup_context.go:71\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).Start\n  | \t/Users/admin/code/milvus-backup/core/backup_context.go:103\n  | github.com/zilliztech/milvus-backup/core.NewServer\n  | \t/Users/admin/code/milvus-backup/core/backup_server.go:42\n  | github.com/zilliztech/milvus-backup/cmd.glob..func7\n  | \t/Users/admin/code/milvus-backup/cmd/server.go:27\n  | github.com/spf13/cobra.(*Command).execute\n  | \t/Users/admin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\n  | github.com/spf13/cobra.(*Command).ExecuteC\n  | \t/Users/admin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\n  | github.com/spf13/cobra.(*Command).Execute\n  | \t/Users/admin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\n  | github.com/zilliztech/milvus-backup/cmd.Execute\n  | \t/Users/admin/code/milvus-backup/cmd/root.go:24\n  | main.main\n  | \t/Users/admin/code/milvus-backup/main.go:17\n  | runtime.main\n  | \t/usr/local/Cellar/go/1.19.2/libexec/src/runtime/proc.go:250\n  | runtime.goexit\n  | \t/usr/local/Cellar/go/1.19.2/libexec/src/runtime/asm_386.s:1326\nWraps: (2) this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="github.com/zilliztech/milvus-backup/core.CreateMilvusClient\n\t/Users/admin/code/milvus-backup/core/backup_context.go:74\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).Start\n\t/Users/admin/code/milvus-backup/core/backup_context.go:103\ngithub.com/zilliztech/milvus-backup/core.NewServer\n\t/Users/admin/code/milvus-backup/core/backup_server.go:42\ngithub.com/zilliztech/milvus-backup/cmd.glob..func7\n\t/Users/admin/code/milvus-backup/cmd/server.go:27\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/admin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/admin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/admin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\ngithub.com/zilliztech/milvus-backup/cmd.Execute\n\t/Users/admin/code/milvus-backup/cmd/root.go:24\nmain.main\n\t/Users/admin/code/milvus-backup/main.go:17\nruntime.main\n\t/usr/local/Cellar/go/1.19.2/libexec/src/runtime/proc.go:250"]

### Environment

```markdown
Milvus 2.2.6 helm k8s deploy
```

**Comment by linggong2023** [comment]
And when I downgrade milvus backup to 0.2.2 .
I backup acollection and recover got zero num entity count

**Comment by zhuwenxing** [comment]
>"failed to connect to milvus"

What is your Milvus server version? Milvus backup v0.3.0 is for Milvus 2.2.9 and above.


>And when I downgrade milvus backup to 0.2.2 .
>I backup acollection and recover got zero num entity count

You can check your backup file in minio and check whether the files contain binlog files.

**Comment by linggong2023** [comment]
My Milvus version is 2.2.6, how could make milvus-backup work

**Comment by zhuwenxing** [comment]
related to https://github.com/zilliztech/milvus-backup/issues/55
The backup bucket name should be the same as the Milvus bucket name.
