### ISSUE TITLE
[Enhancement]:Add optional parameters to limit backup speed

### ISSUE THREAD

**Issue by bedivere2018** [zilliztech/milvus-backup#145]
### What would you like to be added?

Add optional parameters to limit backup speed.

### Why is this needed?

We deployed MinIO and Milvus on the same 5 servers.
When deploying Milvus initially, we did not consider the issue of network bandwidth and therefore defaulted to using a 1-gigabit network card. 
Currently, every time a backup is performed, it occupies the entire network card bandwidth, which affects the normal use of Milvus and can even lead to failures. 
Is there any way to limit the backup speed of Milvus-Backup to alleviate the pressure on the network card bandwidth? 
Slower backups are okay, but they can't affect the Milvus service.

**Comment by wayblink** [comment]
Hi, @bedivere2018 which step costs a large bandwidth, backup or restore?  Could you post a screenshot of  bandwidth monitor or stats during that time?

**Comment by bedivere2018** [comment]
> Hi, @bedivere2018 which step costs a large bandwidth, backup or restore? Could you post a screenshot of bandwidth monitor or stats during that time?

@wayblink , thanks for your reply.

During my scenario, the bandwidth was fully occupied during backup, but this did not happen during the restore process. 
The "minio" address in backup.yaml is the load balancing proxy address, and the Byte traffic on one of the nodes' network cards was monitored as below.
![image](https://github.com/zilliztech/milvus-backup/assets/41724669/9f64f2b4-1779-4531-ab81-37ead7afb9a9)

**Comment by wayblink** [comment]
@bedivere2018 Sorry!!! I miss this comment for a long time. backup copy files concurrently using a worker pool. I think we can support adding a config in backup.yaml to control the pool size. What do you think?

**Comment by bedivere2018** [comment]
> @bedivere2018 Sorry!!! I miss this comment for a long time. backup copy files concurrently using a worker pool. I think we can support adding a config in backup.yaml to control the pool size. What do you think?

@wayblink 
If the size of the pool can affect the speed of copying files, then it should be useful. 
Thank you very much!

**Comment by wayblink** [comment]
Now we have `backup.parallelism.copydata` config to control the backup concurrency.
