### ISSUE TITLE
[Bug]: Only metadata backed up (Ceph S3)

### ISSUE THREAD

**Issue by punkerpunker** [zilliztech/milvus-backup#176]
### Current Behavior

**Milvus version**: 2.2.9
**Milvus-backup version**: 0.3.1

Running milvus-backup tool for a milvus cluster deployed on k8s (baremetal). 

Among other logs, I am seeing an extensive amount of:
```
[2023/08/09 15:46:02.178 +00:00] [WARN] [core/backup_impl_create_backup.go:443] ["this may be old segments before flush, skip it"] [id=443168155094843286]
```

and 
```
[2023/08/09 15:46:03.363 +00:00] [WARN] [core/backup_impl_create_backup.go:468] ["this segment has no insert binlog"] [id=443168155396182316]
```

And then, my backup contains metadata only. 

### Expected Behavior

Backup contains not only metadata, but the data itself as well

### Environment

My backup.yaml: 
```markdown
log:
  level: info # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true
  file:
    rootPath: "logs/backup.log"

http:
  simpleResponse: true

# milvus proxy address, compatible to milvus.yaml
milvus:
  address: milvus.milvus.svc.cluster.local
  port: 19530
  authorizationEnabled: false
  tlsMode: 0
  user: "root"
  password: "Milvus"

minio:
  address: ##### (Ceph)
  port: 443
  accessKeyID: ####
  secretAccessKey: ####
  useSSL: true # Access to MinIO/S3 with SSL
  useIAM: false
  cloudProvider: "aws"
  iamEndpoint: ""
  bucketName: "mlops-milvus-prod-prague"
  rootPath: ""
  backupBucketName: "mlops-milvus-prod-prague-bucket"
  backupRootPath: "backup"
backup:
  maxSegmentGroupSize: 2G
```

My folder structure in S3 is as follows:
```
s3.ObjectSummary(bucket_name='mlops-milvus-prod-prague', key='index_files/443168155091753550/1/443168155091553369/443168155091553381/IVF'
```

(So root folder is the bucket's root)

### Anything else?

I just want to clarify that that's indeed some BUG and not just me doing something wrong. When this is clear - I can take a look myself at the codebase to try to figure out the issue.

**Comment by punkerpunker** [comment]
Would assume that this forms insertPath inappropriately with empty rootPath: 

https://github.com/zilliztech/milvus-backup/blob/f276c61cb370244670edad3ea351f84cf1b01781/core/backup_impl_create_backup.go#L730

Can try to test and fix myself @wayblink, let me know if you think that's an appropriate assumption

**Comment by wayblink** [comment]
@punkerpunker Hi, Thanks! We have tested empty root path on minio/S3. I guess it may caused by different behavior about '/'. Obviously your patch can make it more compatible. Let's test and verify this.
