### ISSUE TITLE
[Enhancement]: support config milvus form env. 

### ISSUE THREAD

**Issue by xushaoxiao** [zilliztech/milvus-backup#178]
### What would you like to be added?

hello teams,

I recently applied the milvus open source project, and made changes to the source code when deploying the backup. I wanted to submit a pr, but the request was denied. Can invite me to join the contributor.

BR.
Shaoxiao.

**Comment by wayblink** [comment]
@xushaoxiao hi, what error you got? It is a public repo, supposed to allow pr from anywhere

**Comment by wayblink** [comment]
@xushaoxiao I guess you need to folk this repo and submit PR instead of submit to this repo directly

**Comment by xushaoxiao** [comment]
hi @wayblink , thank you. you are right. i want to submit pr for code review.

**Comment by xushaoxiao** [comment]
> @xushaoxiao I guess you need to folk this repo and submit PR instead of submit to this repo directly

I try push my fix branch, but got "ERROR: Permission to zilliztech/milvus-backup.git denied to xushaoxiao.
fatal: Could not read from remote repository."
