### ISSUE TITLE
[Feature]:Backup index file

### ISSUE THREAD

**Issue by WuYiFan0108** [zilliztech/milvus-backup#181]
### Is your feature request related to a problem? Please describe.

It takes some time to recreate index after restoring backup especially when having a large collection, which means the service will be unavailable for quit a long time. So, I wonder if there is any plan to support index file backup for Milvus-backup in the future?

### Describe the solution you'd like.

Milvus-backup support index file backup.

**Comment by wayblink** [comment]
Sorry, it is not on the roadmap. Because restore is implemented by recreate a new collection and bulkinsert data into it. The data organization has changed so that the old index file can't apply to new data.

**Comment by WuYiFan0108** [comment]
Understand.
