### ISSUE TITLE
[Enhancement]:milvus备份不能备份索引

### ISSUE THREAD

**Issue by master006** [zilliztech/milvus-backup#185]

**Comment by master006** [comment]
用backup工具，希望也能备份索引

**Comment by wayblink** [comment]
@master006 Sorry. Currently it is not on the roadmap because of implement difficulty.

**Comment by orrn** [comment]
I hope to support restore of the IndexParams of the scaler index.

**Comment by wayblink** [comment]
> I hope to support restore of the IndexParams of the scaler index.

It is supported, any problem you meet?

**Comment by master006** [comment]
我还希望能向Navicat那样数据库之间能够相互备份导入
&nbsp;


F007
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月8日(星期天) 下午4:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zilliztech/milvus-backup] [Enhancement]:milvus备份不能备份索引 (Issue #185)





  
I hope to support restore of the IndexParams of the scaler index.
  
It is supported, any problem you meet?

**Comment by master006** [comment]
需要下载最新backup工具吗？我看最新还是8月份的&nbsp;v0.3.2版本




F007
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zilliztech/milvus-backup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月8日(星期天) 下午4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zilliztech/milvus-backup] [Enhancement]:milvus备份不能备份索引 (Issue #185)





  
I hope to support restore of the IndexParams of the scaler index.
  
It is supported, any problem you meet?

**Comment by master006** [comment]
有问题，我用的milvus-backup 0.4.0 我的milvus版本是2.2.8，备份没问题，恢复报&nbsp;fail to list databases, err: feature not supported 错误，麻烦您看下怎么回事能否解决这个问题，谢谢。




F007
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zilliztech/milvus-backup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月8日(星期天) 下午4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zilliztech/milvus-backup] [Enhancement]:milvus备份不能备份索引 (Issue #185)





  
I hope to support restore of the IndexParams of the scaler index.
  
It is supported, any problem you meet?

**Comment by wayblink** [comment]
@master006 2.2.8->2.2.9 has a large update about database support. 2.2.8 may have no ListDatabases interface. You have to use old version(0.2.2) milvus-backup to backup/restore 2.2.8. Highly recommend to upgrade milvus to newer version 2.2.14+
