### ISSUE TITLE
[Bug]: milvus-backup can't automatically generate backup name

### ISSUE THREAD

**Issue by WuYiFan0108** [zilliztech/milvus-backup#188]
### Current Behavior

The output of `./milvus-backup create -h` shows that milvus-backup can automatically generate a name if backup name is unset. But when I try `./milvus-backup create` or `./milvus-backup create -n`, neither works. The former reports that `collection BACKUP_NAME should not be empty`, the latter reports that `flag needs an argument: 'n' in -n`.

Am I using it the wrong way or is it an unimplemented feature or is it a bug?

### Anything else?

If it's an unimplemented feature or a bug, I'm happy to help.

**Comment by wayblink** [comment]
@WuYiFan0108 Hi, thanks. Yes, it is an unimplemented feature. Welcome to contribute! You can define a default name format, I think it should contain explicit date.

**Comment by WuYiFan0108** [comment]
May be we can just simply use "backup_<time.Now().UnixNano()>" as the default name?
