### ISSUE TITLE
[Feature]: Enable JSONPath or alternative to pass backup configuration as CLI Arguments

### ISSUE THREAD

**Issue by ganderaj** [zilliztech/milvus-backup#204]
### Is your feature request related to a problem? Please describe.

We are developing an automation to trigger backup creation for different Milvus DBs across our PRD and DEV Milvus environments on a scheduled basis.

Thinking is, we maintain a single copy of `milvus-backup` and corresponding backup config and pass backup arguments like S3 Bucket, backup and log path as CLI flags. However, tool doesn't support passing backup configuration forcing us to update `backup.yaml` every time or having to maintain multiple such config files.

### Describe the solution you'd like.

It'd help us if tool provides support for passing backup configuration dynamically. Think in the lines of how you'd pass _"values"_ for helm charts via CLI.

Ideally, a user should be able to trigger backup using below command

`./milvus-backup create -n <backup_name> -d <DB_name> --set minio.backupBucketName=<Bucket_name> --set log.file.rootpath=</PATH/TO/backup-$(date +%y%m%d%H%M)>`

### Describe an alternate solution.

Above is laid out keeping helm into consideration.

Alternate solution would be like that of K8s, using JSONPath.

**Comment by wayblink** [comment]
@ganderaj Hi, it is a reasonable suggestion. Contribution is welcomed. We can put it into our roadmap, but it won't be done very soon
