### ISSUE TITLE
[Bug]: Restore backup failed with error 

### ISSUE THREAD

**Issue by suchenghui** [zilliztech/milvus-backup#205]
### Current Behavior

./milvus-backup restore -n backup_table_one -s _recover

error info：panic: this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server  

### Environment

```markdown
./milvus-backup Version: 1.0-beta
https://github.com/zilliztech/milvus-backup/releases/download/v0.3.3/milvus-backup_Linux_x86_64.tar.gz

restore milvus_cluster_Version: v2.3
```

**Comment by wayblink** [comment]
I will try reproduce it
