### ISSUE TITLE
[Feature]:Restore suceessfully，but dosenot exit the data，just collection definition 

### ISSUE THREAD

**Issue by Jz-Lin** [zilliztech/milvus-backup#241]
### Is your feature request related to a problem? Please describe.

milvus version:2.2.14
backup & restore ,but not found data,just collection definition ,entity count is zero
milvus-backup create -n milvus_bakcup_1031_2
milvus-backup restore -n milvus_bakcup_1031_2
bakcup file: 
![56c8dfdfe7326768d747804f1755b58](https://github.com/zilliztech/milvus-backup/assets/65804252/b287330d-0df7-41e6-bf86-5d5edf9d002d)
![image](https://github.com/zilliztech/milvus-backup/assets/65804252/5d0250a6-7e40-41f5-a418-4403d8e9644b)

**Comment by IshanFernandoClouda** [comment]
https://github.com/zilliztech/milvus-backup/blob/69c09058b190d0ca79d47137b42ead3beabbc50a/configs/backup.yaml#L34-L42

Make sure that the bucket names are correct

**Comment by Jz-Lin** [comment]
the bakcup names is the same as the milvus instance config
but the bakcuk file also just have meta dir, no binlogs dir
![b9a1600b2563170eea9d23beee7e65e](https://github.com/zilliztech/milvus-backup/assets/65804252/040eebd5-010d-46df-95ac-fcb65dce1183)
![0b4db440980644e52e8117a182f1625](https://github.com/zilliztech/milvus-backup/assets/65804252/ac107b6e-5c33-4a2a-8d44-fcfd1022ee20)

![b9a1600b2563170eea9d23beee7e65e](https://github.com/zilliztech/milvus-backup/assets/65804252/eb5ebf47-b885-41ce-8b23-b28a0b4a82d4)

**Comment by zhuwenxing** [comment]
Collection definition is the metadata of collection, and it stores in etcd. so even though your minio config wrong, backup tools can still get them.
But binlog(or segment) is stored in minio, so if the minio config is wrong, there will no data restore.

From the screenshots, most likely, your minio bucketName or rootpath is not right.

**Comment by wayblink** [comment]
> is there any command that i can test the minio bucketName or rootpath on backup config file is right ?

You can use `milvus-backup check` command to verify your connections

**Comment by zhuwenxing** [comment]
> is there any command that i can test the minio bucketName or rootpath on backup config file is right ?

You can get the info of minio from the `mulvus.yaml` in milvus pod or container if you have permission.

**Comment by Jz-Lin** [comment]
yes,  i write the same as the mulvus.yaml in milvus pod before . mulvus.yaml  rootPath is /root.
now i change the bakcup.yaml , set rootPath : root  ,   it backup sucessfully.
