### ISSUE TITLE
[Typo]: change minio.cloudprovider comments to correctly reflect accepted cloudproviders in config.yaml

### ISSUE THREAD

**Issue by mcandio** [zilliztech/milvus-backup#258]
The config files accepts s3 as a cloud provider but params.go expects "aws" instead https://github.com/zilliztech/milvus-backup/blob/52143599b05435cda4fac8266ef0143e19db8d1e/core/paramtable/params.go#L148

It also suggests aliyun but params.go expects ali. https://github.com/zilliztech/milvus-backup/blob/52143599b05435cda4fac8266ef0143e19db8d1e/core/paramtable/params.go#L150

Config.yaml file: https://github.com/zilliztech/milvus-backup/blob/52143599b05435cda4fac8266ef0143e19db8d1e/configs/backup.yaml#L24

**Comment by wayblink** [comment]
@mcandio Hi, nice catch, I will fix it
