### ISSUE TITLE
[API]There is no `state_code` field in data for `get_restore` API when restore is ongoing

### ISSUE THREAD

**Issue by zhuwenxing** [zilliztech/milvus-backup#27]
When the restore is completed, the state code is `2`, but when the restore is ongoing,  there is no `state code` field.

```
{
    "requestId": "c41a39b2-6fbd-11ed-824c-acde48001122",
    "msg": "success",
    "data": {
        "id": "ed89a252-6fbc-11ed-824c-acde48001122",
        "start_time": 1669709274
    }
}
```
The API `get_backup` will return state_code as 1 when creating  backup is ongoing

**Comment by wayblink** [comment]
nice catch. fixed in #28
