### ISSUE TITLE
[Bug]: Using the API to back up the collection, it is found that the quantity of backups has always been 0

### ISSUE THREAD

**Issue by jiaochuangen** [zilliztech/milvus-backup#276]
### Current Behavior

![6bc8dec8ad28d63c06f053e4d27ef6e](https://github.com/zilliztech/milvus-backup/assets/53078519/d5244926-0100-45ed-b1d8-193b3908ae3a)
![8a8ba54f9d3a3cb6bd0f7e7858effee](https://github.com/zilliztech/milvus-backup/assets/53078519/b005ca55-45f8-42dc-aa0c-40854d31abee)
Why is the size 0?

### Expected Behavior

display normally

### Environment

```markdown
milvus: v2.2.11 doker/standalone
milvus-backup source:git clone https://github.com/zilliztech/milvus-backup.git
go: go version go1.20.12 linux/amd64
```

**Comment by zhuwenxing** [comment]
try asnyc=false in your payload

**Comment by jiaochuangen** [comment]
> try asnyc=false in your payload



> try asnyc=false in your payload

**Comment by zhuwenxing** [comment]
Some questions: 
1. What is the version of Milvus backup?
 2. Can the backup restore the correct data? 

The above logs are Milvus logs， so it would be better to offer the Milvus backup service log.
