### ISSUE TITLE
[Bug]: 使用向量查询时，相同的向量查询的相似度相差甚远，使用cos计算的为0.999999，milvus查询的则为0.81，0.91

### ISSUE THREAD

**Issue by silencesmile** [zilliztech/milvus-backup#278]
### Current Behavior

在使用向量聚类时，产生聚类中心向量，将向量插入milvus，向量数值有向量不一致(小数点最后几位)，再使用同样的向量查询时，相似度仅为0.81，即使是复制的milvus库中存下来的向量，相似度也是0.8多， 当使用cos计算向量，相似度为0.9999，如果使用milvus查询相似度topn，结果误差很大。
![1111](https://github.com/zilliztech/milvus-backup/assets/11863270/844f036e-d92e-44fe-b8b4-3960a84377a8)
![222222](https://github.com/zilliztech/milvus-backup/assets/11863270/a645189d-1363-4744-b8c7-b1c2bfa0fc26)
[python_cos_similarity.py.txt](https://github.com/zilliztech/milvus-backup/files/13868492/python_cos_similarity.py.txt)

### Expected Behavior

希望相同的向量查询的相似度为1.0

### Steps To Reproduce

```markdown
1、打开txt文件，修改为.py文件
2、执行py文件，得到相似度为0.9999
3、将py文件里的向量插入milvus
4、使用另一组向量或插入的向量查询milvus的相似度
5、得到相似度结果为0.81
```

### Environment

```markdown
Python执行环境：3.10
milvus版本为：2.3.x
```

**Comment by zhuwenxing** [comment]
You can open issue here https://github.com/milvus-io/milvus/issues for the Milvus issue

**Comment by silencesmile** [comment]
好的  已处理
