### ISSUE TITLE
[Bug]: Only backup meta

### ISSUE THREAD

**Issue by gaoyuan5251** [zilliztech/milvus-backup#282]
### Current Behavior

backup milvus-standalone-2.3.1 

### Expected Behavior

[backup (2).log](https://github.com/zilliztech/milvus-backup/files/14047863/backup.2.log)
[backup (1).yaml.log](https://github.com/zilliztech/milvus-backup/files/14047867/backup.1.yaml.log)

**Comment by wayblink** [comment]
大概率配置错了，检查rootpath和bucket是否和milvus一致。 可以执行下check命令

**Comment by gaoyuan5251** [comment]
> 大概率配置错了，检查rootpath和bucket是否和milvus一致。 可以执行下check命令

解决了，应该是该目录的上一级目录才对。我的rootpath 不是files，这个参数不对。感谢
![image](https://github.com/zilliztech/milvus-backup/assets/38758293/09ec00f1-3040-4df7-bebd-a097e9f3655d)
