### ISSUE TITLE
Milvus Backup And Restoration (milvus is running as a cluster)

### ISSUE THREAD

**Issue by omgupta240909** [zilliztech/milvus-backup#283]
Hello,
I am Running a milvus cluster Running on k8s, my ETCD and Minio are running Outside the cluster they are running on the seprate namespace.
so what is the backup strategy do i follow and how do i restore the data.

**Comment by zhuwenxing** [comment]
just make sure your backup can access etcd, minio, and milvus.

**Comment by omgupta240909** [comment]
@zhuwenxing it is running on the same machine . will milvus backup  can take the backup of ETCD and minio??
if not then what is the best case scenario to took the backup.

**Comment by wayblink** [comment]
> @zhuwenxing it is running on the same machine . will milvus backup can take the backup of ETCD and minio?? if not then what is the best case scenario to took the backup.

I think backup can work as long as your milvus can work in this way.

**Comment by name814477** [comment]
@zhuwenxing is it possible to take backup of etcd and minio on nfs or differnet minio cluster (not original one where milvus storing data )

**Comment by wayblink** [comment]
> @zhuwenxing is it possible to take backup of etcd and minio on nfs or different minio cluster (not original one where milvus storing data )

Not sure about NFS. Maybe you can try it. Backup actually implemented by call Copy API. I think we can't call COPY across file system unless you have a upper level service in your business.

**Comment by wayblink** [comment]
> @zhuwenxing is there any provision to backup (etcd and minio)in some local file and restore the same.

Backup actually implemented by call Copy API. So you have to download file from minio to local manually.
