### ISSUE TITLE
[DOCS]:  配置文件中的storageType是什么意思

### ISSUE THREAD

**Issue by papandadj** [zilliztech/milvus-backup#285]
### Describe the improvement

<img width="941" alt="image" src="https://github.com/zilliztech/milvus-backup/assets/25424898/a1f1bd73-5f07-4ad4-bca4-c2ffdc700631">
你好，我对配置文件有点疑问，这里面写的可以选择local，我选择local后报错了"Fail to fill segment backup info"。

有没有备份时，把数据备份到本地的选项。而不是在minio中拷贝一份

**Comment by JackLCL** [comment]
当你的milvus是部署在本地磁盘上的，没有使用MiniIO，那么使用backup工具备份出来的文件也是放在本地磁盘上的，此时storageType才能填成 local。

**Comment by papandadj** [comment]
谢谢你，马龙。哪如果我的源milvus用的minio存储，我想备份到本地磁盘，然后带着磁盘文件恢复到目标milvus（minio存储）中，可以吗？

**Comment by JackLCL** [comment]
这样是可以的，你需要先备份到源milvus用的minio存储，然后把数据从备份桶里下载下来，然后上传到目标milvus的minio存储桶中。之前写过一篇关于backup的使用指南，你可以参考下：https://mp.weixin.qq.com/s/nSnGcVXbfZZYfRQeic7zDA

**Comment by papandadj** [comment]
好的 谢谢
