### ISSUE TITLE
[Bug]: fail to flush the collection: knowledge_base

### ISSUE THREAD

**Issue by Xcrab** [zilliztech/milvus-backup#311]
### Current Behavior

![bug](https://github.com/zilliztech/milvus-backup/assets/20314873/e666f8f6-df3c-46ae-b0cb-1c4e2dc43fe5)

### Steps To Reproduce

```markdown
I want to backup milvus data, but milvus_backup always says "fail to flush the collection".

btw, I found that, When the milvus gets stuck in an exception for some reason(No space left on device、reboot linux), milvus displays error logs(reason=Timestamp lag too large") for a long time. why ?
```

**Comment by wayblink** [comment]
@Xcrab It is a Milvus issue, please ask it in milvus repo or discord(https://discord.com/channels/1160323594396635310).
