### ISSUE TITLE
[Enhancement]: Add the etcd also as part of backup

### ISSUE THREAD

**Issue by kish5430** [zilliztech/milvus-backup#320]
### What would you like to be added?

The backup tool currently only backs up collection files from the S3 bucket. Its better to add etcd backup along with collections and its indexes.

### Why is this needed?

Back tool is not backing up etcd.  Milvus restricts root access to etcd, making it impossible to back up. Even if we had root access, it would be preferable to back up etcd along with its collection to save effort and avoid separate backups

**Comment by wayblink** [comment]
Now, there is no strong need to backup etcd. Milvus-backup get essential metadata through Milvus SDK. Contributions are welcome.

**Comment by wayblink** [comment]
close as it will not supported
