### ISSUE TITLE
[Bug]: 在milvus:v2.3.9，使用milvus-backup:v0.4.12进行恢复，只能恢复元数据，无法恢复数据

### ISSUE THREAD

**Issue by yandechao** [zilliztech/milvus-backup#328]
### Current Behavior

用milvus-backup(版本v0.3.3)在milvus(版本v2.2.11)进行备份数据。
用milvus-backup(版本v0.4.12)在milvus(版本v2.3.9)进行恢复数据，发现只恢复了元数据，无法恢复数据。

### Steps To Reproduce

```markdown
用milvus-backup(版本v0.3.3)在milvus(版本v2.2.11)备份数据。
用milvus-backup(版本v0.4.12)在milvus(版本v2.3.9)恢复数据，发现只恢复了元数据，无法恢复数据。
```

### Environment

```markdown
备份时的环境：
milvus-backup(版本v0.3.3)
milvus(版本v2.2.11)

恢复时的环境：
milvus-backup(版本v0.4.12)
milvus(版本v2.3.9)
```

**Comment by wayblink** [comment]
有试过用最新版本备份恢复吗 提供下日志？

**Comment by yandechao** [comment]
[milvus-exp.logs.txt](https://github.com/zilliztech/milvus-backup/files/15281411/milvus-exp.logs.txt)
[milvus-imp.logs.txt](https://github.com/zilliztech/milvus-backup/files/15281414/milvus-imp.logs.txt)
@wayblink 
milvus-exp.logs.txt是导出日志，使用milvus-backup(版本v0.3.3)在milvus(版本v2.2.11)进行备份数据。
milvus-imp.logs.txt是导入日志，使用milvus-backup(版本v0.4.12)在milvus(版本v2.3.9)进行恢复数据，发现只恢复了元数据，无法恢复数据。
