### ISSUE TITLE
[Feature]: support data migration

### ISSUE THREAD

**Issue by erigo** [zilliztech/milvus-backup#332]
### Describe the solution you'd like.

1. Export data to local storage.
2. Import data to the new milvus.

**Comment by wayblink** [comment]
@erigo 
Hi, currently you can export data to local by storage client. I guess you think it is not convenient enough. To support cross storage backup, the backup service has to handle the data IO. This will brings many new points to think and design. It is on our long term roadmap, won't come very soon. Welcome to contribute ~ 

For "Import data to the new milvus", do you know bulkinsert (https://milvus.io/docs/v2.3.x/bulk_insert.md). Is that what you need？
