### ISSUE TITLE
[Feature]: Provide the official Milvus Backup image.

### ISSUE THREAD

**Issue by erigo** [zilliztech/milvus-backup#337]
### Is your feature request related to a problem? Please describe.

We need to use Milvus-Backup in Kubernetes (k8s) cluster.

**Comment by zhuwenxing** [comment]
https://hub.docker.com/r/milvusdb/milvus-backup/tags

**Comment by erigo** [comment]
Add installation in README.md?  :-)

**Comment by erigo** [comment]
@zhuwenxing
