### ISSUE TITLE
[Feature]: Add `version` command for CLI

### ISSUE THREAD

**Issue by zhuwenxing** [zilliztech/milvus-backup#35]
### Is your feature request related to a problem? Please describe.

In most CLI tools, we can show the version of it by `xxx version (xxx -v)`, like kubectl, helm, and so on
```
 helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

When the tool has the version, the user can report bugs more conveniently for the specific version.

### Describe the solution you'd like.

The most common way is by using `-ldflags` to inject the info to the variable when building with Makefile

refer:
https://web3.coach/golang-include-last-git-commit-in-your-go-program-version

Here is a backup tool repo for a nebula graph database: https://github.com/vesoft-inc/nebula-br

**Comment by wayblink** [comment]
added in #52
