### ISSUE TITLE
[Bug]: Error when create backup a collection in dataset

### ISSUE THREAD

**Issue by lenguyenphuhuuo** [zilliztech/milvus-backup#359]
### Current Behavior

When I run
```
 milvus-backup create -n selling_test_collection_demo_05 -a {'content': ['company_590']} --config selling-stage_milvus_config.yaml
 ```
 We get this error
 [ERROR] [core/backup_impl_create_backup.go:148] ["fail in unmarshal dbCollections in CreateBackupRequest"] [dbCollections={content:] [error="ReadString: expects \" or n, but found c, error found in #2 byte of ...|{content:|..., bigger context ...|{content:|..."] [stack="github.com/zilliztech/milvus-backup/core.(*BackupContext).parseBackupCollections\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_create_backup.go:148\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).executeCreateBackup\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_create_backup.go:615\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).CreateBackup\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_create_backup.go:112\ngithub.com/zilliztech/milvus-backup/cmd.glob..func3\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/create.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\ngithub.com/zilliztech/milvus-backup/cmd.Execute\n\t/home/runner/work/milvus-backup/milvus-backup/cmd/root.go:35\nmain.main\n\t/home/runner/work/milvus-backup/milvus-backup/main.go:24\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250"]

**Comment by wayblink** [comment]
@lenguyenphuhuuo the parameter is a json. try like this:
```
milvus-backup create -n selling_test_collection_demo_05 -a "{\"content\":[\"company_590\"]}"
```

**Comment by lenguyenphuhuuo** [comment]
@wayblink thank you. It's work.
