### ISSUE TITLE
[Bug]: Backup tool is not restoring all collections from a database.

### ISSUE THREAD

**Issue by kish5430** [zilliztech/milvus-backup#378]
### Current Behavior

In a multi-tenency cluster, have mulitiple databases. when i tried to restore the all collections from a database, its not restoring.

curl --location --request POST 
'https://xxxxxxxxxxxxxxxxxxxx/api/v1/restore' \
--header 'Content-Type: application/json' \
--data-raw '{
    "async": true,
    "collection_suffix": "test_db.*",
    "backup_name":"complete_backup_20240703000003"
}'

### Expected Behavior

It should restore all collections from test_db.

**Comment by wayblink** [comment]
@kish5430 Please read `help` in cli or swagger UI in rest service. Use params in the right way.

**Comment by kish5430** [comment]
@wayblink I have read the documentation and couldn't find the solution. My question is: Can I restore all collections from a database in a multi-tenancy cluster without listing all the collection names? I want to use a pattern matching approach.
