### ISSUE TITLE
[Bug]:  backup error

### ISSUE THREAD

**Issue by CyanMystery** [zilliztech/milvus-backup#379]
### Current Behavior

[ERROR] [core/backup_impl_create_backup.go:361] ["fail to flush the collection"] [databaseName=default] [collectionName=my_b] [error="channel not found[channel=by-dev-rootcoord-dml_11_451014385621535341v0]"] [errorVerbose="channel not found[channel=by-dev-rootcoord-dml_11_451014385621535341v0]\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus-sdk-go/v2/client.handleRespStatus\n  | \t/root/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.3.0-beta4.0.20240607085051-1ac5aaf24c6d/client/collection.go:39\n  | github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).FlushV2\n  | \t/root/go/pkg/mod/github.com/wayblink/milvus-sdk-go/v2@v2.3.0-beta4.0.20240607085051-1ac5aaf24c6d/client/insert.go:213\n  | github.com/zilliztech/milvus-backup/core.(*MilvusClient).FlushV2\n  | \t/root/milvus-backup/core/milvus_sdk_wrapper.go:94\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).backupCollectionPrepare\n  | \t/root/milvus-backup/core/backup_impl_create_backup.go:359\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).executeCreateBackup.func1.1\n  | \t/root/milvus-backup/core/backup_impl_create_backup.go:674\n  | github.com/zilliztech/milvus-backup/internal/util/retry.Do\n  | \t/root/milvus-backup/internal/util/retry/retry.go:37\n  | github.com/zilliztech/milvus-backup/core.(*BackupContext).executeCreateBackup.func1\n  | \t/root/milvus-backup/core/backup_impl_create_backup.go:673\n  | github.com/zilliztech/milvus-backup/internal/common.(*WorkerPool).work.func1\n  | \t/root/milvus-backup/internal/common/workerpool.go:70\n  | golang.org/x/sync/errgroup.(*Group).Go.func1\n  | \t/root/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75\n  | runtime.goexit\n  | \t/usr/local/golang/go/src/runtime/asm_amd64.s:1695\nWraps: (2) channel not found[channel=by-dev-rootcoord-dml_11_451014385621535341v0]\nError types: (1) *withstack.withStack (2) *errutil.leafError"] [stack="github.com/zilliztech/milvus-backup/core.(*BackupContext).backupCollectionPrepare\n\t/root/milvus-backup/core/backup_impl_create_backup.go:361\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).executeCreateBackup.func1.1\n\t/root/milvus-backup/core/backup_impl_create_backup.go:674\ngithub.com/zilliztech/milvus-backup/internal/util/retry.Do\n\t/root/milvus-backup/internal/util/retry/retry.go:37\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).executeCreateBackup.func1\n\t/root/milvus-backup/core/backup_impl_create_backup.go:673\ngithub.com/zilliztech/milvus-backup/internal/common.(*WorkerPool).work.func1\n\t/root/milvus-backup/internal/common/workerpool.go:70\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/root/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75"]

### Steps To Reproduce

```markdown
./milvus-backup create -n my_backup
```

### Environment

```markdown
milvis v2.4.0-rc.1
```

### Anything else?

backup.yaml:

minio:
  # cloudProvider: "minio" # deprecated use storageType instead
  storageType: "minio" # support storage type: local, minio, s3, aws, gcp, ali(aliyun), azure, tc(tencent)

  address: localhost # Address of MinIO/S3
  port: 9000   # Port of MinIO/S3
  accessKeyID: minioadmin  # accessKeyID of MinIO/S3
  secretAccessKey: minioadmin # MinIO/S3 encryption string
  useSSL: false # Access to MinIO/S3 with SSL
  useIAM: false
  iamEndpoint: ""

  bucketName: "a-bucket" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
  rootPath: "files" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance

Check backetName, rootPath and milvus for consistency

**Comment by ht2324** [comment]
How to solve it in the end @CyanMystery

**Comment by ht2324** [comment]
> How to solve it in the end [@CyanMystery](https://github.com/CyanMystery)

@wayblink please help

**Comment by huanghaoyuanhhy** [comment]
Hi, @ht2324 

Could you please share the exact error message or a screenshot of the issue? This will help us better understand and troubleshoot the problem. Thank you!

**Comment by ht2324** [comment]
> Hi, [@ht2324](https://github.com/ht2324)
> 
> Could you please share the exact error message or a screenshot of the issue? This will help us better understand and troubleshoot the problem. Thank you!
when run the backup cmd
logs：
[2025/05/09 14:44:55.072 +08:00] [ERROR] [core/backup_impl_create_backup.go:401] ["fail to flush the collection"] [databaseName=faces] [collectionName=Celebrity_recover] [error="client: flush failed: client: operation failed: error_code:UnexpectedError  reason:\"channel not found[channel=by-dev-rootcoord-dml_4_451836593227904432v0]\"  code:500  detail:\"channel not found[channel=by-dev-rootcoord-dml_4_451836593227904432v0]\""] [stack="github.com/zilliztech/milvus-backup/core.(*BackupContext).backupCollectionPrepare\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_create_backup.go:401\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).executeCreateBackup.func1.1\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_create_backup.go:690\ngithub.com/zilliztech/milvus-backup/core.(*BackupContext).executeCreateBackup.func1\n\t/home/runner/work/milvus-backup/milvus-backup/core/backup_impl_create_backup.go:706\ngithub.com/zilliztech/milvus-backup/internal/common.(*WorkerPool).work.func1\n\t/home/runner/work/milvus-backup/milvus-backup/internal/common/workerpool.go:71\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/runner/go/pkg/mod/golang.org/x/sync@v0.10.0/errgroup/errgroup.go:78"]

and The collection has been in the process of loading 50% of the time

**Comment by huanghaoyuanhhy** [comment]
Hello @ht2324 

The error message you provided — `channel not found[channel=by-dev-rootcoord-dml_4_451836593227904432v0]` — suggests that the message queue (MQ) may be experiencing issues, which is causing certain channels to be missing or inaccessible.

If you still need to perform a backup under these circumstances, you can bypass the Flush phase by using the following command:

`./milvus-backup create -f`

This option will skip the data flush step and proceed with the backup directly. Please be aware that doing so may result in the loss of some in-mq data that hasn't been persisted yet. However, when the MQ is already malfunctioning, this is often the only viable approach.
