### ISSUE TITLE
backup failed between different db in the one milvus

### ISSUE THREAD

**Issue by dorne-shi** [zilliztech/milvus-backup#390]
When backup is performed between the two db , the number of collections is 1. When backup is performed between different db , the number of collections is 0. What is the problem? 
<img width="1675" alt="image" src="https://github.com/user-attachments/assets/6652736f-d74d-41a1-8aa0-1ef6be4177bf">
![151723106223_ pic](https://github.com/user-attachments/assets/674ffa6d-d772-48b4-871a-62298e699013)
["Collections to restore"] [collection_num=0] this log

**Comment by dorne-shi** [comment]
The "db" here is "restore - a" was brought in, "collectionBackup.GetDbName()" is "create -a" was brought in, both equal, it is not possible because the background is the same between different db cluster synchronization; So is there a problem here?
<img width="1226" alt="image" src="https://github.com/user-attachments/assets/24b62782-5369-40fa-9d2d-4918ac0d2775">

**Comment by wayblink** [comment]
@dorne-shi please execute `./milvus-backup get -n backup` and paste output here

**Comment by dorne-shi** [comment]
<img width="1674" alt="image" src="https://github.com/user-attachments/assets/02526494-d6f6-4c07-b77b-5117aef766fe">

**Comment by wayblink** [comment]
@dorne-shi Sorry to miss your reply. Has the problem been solved? use your own {backup_name}, not just 'backup'.
