### ISSUE TITLE
[Bug]: 备份时只备份了meta， 未备份数据

### ISSUE THREAD

**Issue by Bbbixia** [zilliztech/milvus-backup#393]
### Current Behavior

milvus_version:\"v2.4.4\" 
milvus-backup version 0.4.15
执行命令：./milvus-backup --config ../configs/backup.yaml create -n test_112
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/74439023-d477-4573-ba84-fc389504cd93">
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/87f2235b-cc31-405e-a9a4-a09c30c0e9c6">
![image](https://github.com/user-attachments/assets/c6aa61f2-1474-43df-982c-b6b5637fd22a)

### Expected Behavior

当前的milvus 中有数据,能够把数据备份出来

**Comment by wayblink** [comment]
大概率配置配错了 执行./milvus-backup check命令检查下

**Comment by Bbbixia** [comment]
ok， 找到原因了, 感谢 .

**Comment by Bbbixia** [comment]
请问索引是一起备份过来， 然后能够恢复出来嘛？

**Comment by 670248996** [comment]
> ok， 找到原因了, 感谢 .

你好，问一下这个是怎么解决的
