### ISSUE TITLE
[Bug]: integer divide by zero

### ISSUE THREAD

**Issue by tgk60w** [zilliztech/milvus-backup#41]
### Current Behavior

./milvus-backup  restore   -n test -s retest
![image](https://user-images.githubusercontent.com/49012823/206109096-19cced81-228f-4ad2-9cd6-4e53b0d35b01.png)

**Comment by zhuwenxing** [comment]
Hi, what is your Milvus version?
The backup function now is only supported for v2.2.0 and above. 

I have tested it in v2.1.0, and it reported the same error.

![image](https://user-images.githubusercontent.com/12268675/206112615-bd6e6f50-94c1-4bac-83b2-b434c292f3ae.png)

**Comment by wayblink** [comment]
I guess you backup and restore an empty collection? There is a bug in progress calculation. Thanks for your feedback.

**Comment by tgk60w** [comment]
> restore



> I guess you backup and restore an empty collection? There is a bug in progress calculation. Thanks for your feedback.

yes,empty collection

**Comment by tgk60w** [comment]
> Hi, what is your Milvus version? The backup function now is only supported for v2.2.0 and above.
> 
> I have tested it in v2.1.0, and it reported the same error. https://github.com/zhuwenxing/milvus-backup/actions/runs/3626475152/jobs/6115504353 ![image](https://user-images.githubusercontent.com/12268675/206112615-bd6e6f50-94c1-4bac-83b2-b434c292f3ae.png)

version 2.2.0

**Comment by zhuwenxing** [comment]
> version 2.2.0
OK! Thanks for the reply, and I have reproduced it in my environment. @wayblink  will fix this bug, and I will add test cases to cover this scenario

**Comment by wayblink** [comment]
@tgk60w fixed in #44 , please try again. Feel free to tell us if you meet other issues.
