### ISSUE TITLE
milvus-backup  are always in the bulkinsert task state 

### ISSUE THREAD

**Issue by 1292253144** [zilliztech/milvus-backup#414]
### Current Behavior

源集群590W数据，使用milvus-backup备份后在另一个集群进行恢复，一直处于 bulkinsert task state循环中，已经进行了3个小时。目标集群中恢复了一个segment，不再继续
![image](https://github.com/user-attachments/assets/2e1cac70-c0d6-418c-9705-07d40fb70926)
![image](https://github.com/user-attachments/assets/dbe353bc-e9a5-428a-a19e-731a456f85f7)

### Expected Behavior

我现在需要做什么可以解决这个问题

### Steps To Reproduce

```markdown
1.源集群 ./milvus-backup create -n  backup_20240902
2.目标集群  ./milvus-backup restore -n  backup_20240902
```

### Environment

```markdown
Milvus版本 2.4.1
milvus-backup版本：0.4.21
```

**Comment by wayblink** [comment]
@1292253144 bulkinsert 进度卡在70表示在建索引了，查一下milvus，看建索引是不是卡住了

**Comment by hiddenvillage** [comment]
遇到了同样的问题，我尝试恢复时不恢复索引，后面手动创建索引，但这样在加载collection时会失败，并且qn会挂掉。
