### ISSUE TITLE
[Bug]: Does backup tool support cross storage **restore**?

### ISSUE THREAD

**Issue by caozhuozi** [zilliztech/milvus-backup#415]
### Current Behavior

We are strugging to use `restore` to replay the data to a **new** milvus cluster. The two clusters are independent and do not share data storage backend/service.

we noticed the recent PR  adding `crossStorage` support but not sure if  it is only a partial support, with `restore` ignored?

**Comment by wayblink** [comment]
@caozhuozi restore is also supported. Please refer to https://github.com/zilliztech/milvus-backup/blob/main/docs/user_guide/cross_storage.md for usage
