### ISSUE TITLE
[Bug]: After backup, how to restore data to another milvus?

### ISSUE THREAD

**Issue by neblen** [zilliztech/milvus-backup#423]
### Current Behavior

After backing up data, I cannot restore it to another milvus. When I connect to another milvus, the backup is not displayed.

**Comment by neblen** [comment]
The current test result is that it is possible to import the milvus backup into the original milvus. I don't know how to import it into another milvus.

**Comment by wayblink** [comment]
@neblen You should move the backup data from source milvus's storage to target milvus's storage. Change the config according to your target cluster and do restore.
