### ISSUE TITLE
Index not found after restoring collection?

### ISSUE THREAD

**Issue by P-Ehlert** [zilliztech/milvus-backup#434]
I am trying to clone a Milvus 2.4.10 standalone installation with 1 collection (58 million entries) from one system to another. Stopping Milvus and copying all files doesn't work. The copied installation will start fine and I can see the collection, but querying will return an error such as `failed to query: segment lacks[segment=449007914226825308]: channel not available[channel=by-dev-rootcoord-dml_0_449007914164859543v0]`.

So instead I tried to use the milvus-backup tool (v0.4.24) and used the examples on the [milvus website](https://milvus.io/docs/milvus_backup_api.md) to make a copy and restore that. Basically what I did is the following: 
1. Configure backup.yaml and set `backupAddress` to the 2nd system where I want to restore the data and set `crossStorage: "true"`.
2. Start milvus-backup on the origin system and create a backup on the 2nd system. 
3. Start milvus-backup (also v0.4.24) on the 2nd system and do a local restore.

After this I can see and connect to the restored collection on the 2nd system. It has the expected number of entries, however when doing a query I get `error code: 700, reason: index not found`. What exactly did I miss? Is there an option somewhere to also copy the index? And isn't there an easier way to clone an installation?

**Comment by wayblink** [comment]
@P-Ehlert Milvus-backup can't backup&restore index data by design. We have to recreate index in the new cluster. You can add `--restore_index` in restore command to let milvus-backup restore the index meta. It takes time to build new index data in the cluster.

**Comment by P-Ehlert** [comment]
Thank you for your help. When using the backup API to start the restore, can I just add something like `"restore_index": true`?

**Comment by wayblink** [comment]
> Thank you for your help @wayblink. When using the backup API to start the restore, can I just add something like `"restore_index": true`? It would be great if there's documentation regarding these options, but I haven't been able to find that.

yes, please browse http://localhost:8080/api/v1/docs/index.html as you set up the server. A swagger UI is provided
