### ISSUE TITLE
[Bug]: 数据备份恢复 找不到插入日志

### ISSUE THREAD

**Issue by gxh-97** [zilliztech/milvus-backup#436]
### Current Behavior

A服务器备份的数据上传至B服务器的minio下
执行其他命令可以找到备份
在执行milvus-backup restore -n xxx 时 出现错误信息 "failed_reason\":\"failed to list insert logs with root path files/cbir_agr/binlogs/insert_log/443089265629978908/443089265629978916/1/, error: The specified bucket does not exist
但是我通过查看minio文件发现该路径是存在的

### Expected Behavior

[log.txt](https://github.com/user-attachments/files/17323358/log.txt)

### Steps To Reproduce

```markdown
1.milvus2.2.3
2.minio2023-03-20T20-16-18Z
3.milvus-backup 0.2.0
```

**Comment by touale** [comment]
Why?
