### ISSUE TITLE
[Feature]: Need arm64 support for docker image

### ISSUE THREAD

**Issue by iamkhalidbashir** [zilliztech/milvus-backup#452]
### Is your feature request related to a problem? Please describe.

No arm64 sypport on docker image
![image](https://github.com/user-attachments/assets/a4951016-2657-4a42-acc0-38c79f1e1366)

**Comment by wayblink** [comment]
@zhuwenxing Can we support this easily?

**Comment by vishesh-monoceros** [comment]
@zhuwenxing any updates on this? This seems to be almost ready in a PR state with 1 test failing. Could we get this merged and a new version pushed for arm and amd? This would make life a lot simpler for many companies out there

**Comment by zhuwenxing** [comment]
https://hub.docker.com/r/milvusdb/milvus-backup/tags
![image](https://github.com/user-attachments/assets/df192295-378d-422c-8e8d-680705bf413a)

done
