### ISSUE TITLE
[Bug]: Can't compile on linux

### ISSUE THREAD

**Issue by Niceies** [zilliztech/milvus-backup#480]
### Current Behavior

I cloned the code, switched to branch v0.4.27, uploaded the code to the Linux environment, and executed the compilation command make all in the document, but the build failed.The error message is as follows
```
scripts/gen_proto.sh: line 10: /home/code/milvus-backup/build/thirdparty/protobuf-build/protoc: cannot execute binary file: Exec format error
```

### Expected Behavior

I can compile successfully

### Environment

```markdown
cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
```
arch
x86_64
```
```


### Anything else?

_No response_

**Comment by huanghaoyuanhhy** [comment]
Thank you for reaching out!
The `gen_proto.sh` script relies on the `protoc` binary located in the `build/thirdparty/protobuf-build/` directory, but unfortunately, this binary is only compatible with macOS ARM environments.

However, the repository already contains the pre-generated `.pb.go` files. If you haven't modified the proto files, you can simply run make build to skip the `.pb.go` generation step.

Please let us know if you encounter any further issues!
