### ISSUE TITLE
How to Write Backup Files to a Local Mount Point

### ISSUE THREAD

**Issue by luliloveshe918** [zilliztech/milvus-backup#483]
Background:
Machine A: Linux, deployed Milvus instance in STANDALONE mode.
Machine A: Mounted a Windows shared directory, mount point: /mnt/win_share, with read/write access.

How to achieve: Directly write the backup files to /mnt/win_share during the backup?
What does backupStorageType="local" mean in the configuration file?
Can it be used to achieve the above requirement?

**Comment by huanghaoyuanhhy** [comment]
Yes, just set the backup storage type to "local". Was the backup successful? Did you encounter any other issues?

**Comment by luliloveshe918** [comment]
The backup of the small table (51 rows) was successful. However, backing up the entire database (several million rows) resulted in an error.
Refer to #487
