### ISSUE TITLE
[Enhancement]: backup impl backup index and load meta, through get backup api can return the meta.

### ISSUE THREAD

**Issue by yelusion2** [zilliztech/milvus-backup#61]
### What would you like to be added?

backup impl backup index and load meta, througn get backup api can return the meta.

### Why is this needed?

user can kown every backup collection index and load status,

and convenient user after restore through the backup meta build index or load collection.

**Comment by wayblink** [comment]
implement in #62

**Comment by wayblink** [comment]
done
