### ISSUE TITLE
[Feature]:Release binary using GoReleaser

### ISSUE THREAD

**Issue by zhuwenxing** [zilliztech/milvus-backup#67]
### Is your feature request related to a problem? Please describe.

As a user, I just want a binary that can execute. I do not want to build it from source code from scratch.

### Describe the solution you'd like.

https://goreleaser.com/
https://github.com/goreleaser/goreleaser

> Release Go projects as fast and easily as possible!
> With GoReleaser, you can:
> 
> Cross-compile your Go project
> Release to GitHub, GitLab and Gitea
> Create nightly builds
> Create Docker images and manifests
> Create Linux packages and Homebrew taps
> Sign artifacts, checksums and container images
> Announce new releases on Twitter, Slack, Discord and others
> Generate SBOMs (Software Bill of Materials) for binaries and container images
> ... and much more!

**Comment by Leslie-Wong-H** [comment]
Agree with this.

<code>go get</code> might be a nightmare for some people without a proper proxy.
