### ISSUE TITLE
[bug]:milvus-backup connects to bucket failed

### ISSUE THREAD

**Issue by citePerson** [zilliztech/milvus-backup#72]
### What would you like to be added?

我想测试milvus的高可用功能，现在是处理单机环境，没有启用集群
1、我新建的bucket
![image](https://user-images.githubusercontent.com/107391111/212256554-f9f26a29-e580-4da7-b36d-55bb57f53573.png)
2、提示我连接失败
![image](https://user-images.githubusercontent.com/107391111/212256727-2933f51d-fc99-4fdf-b39e-bf5b466c65c3.png)
3、这是我的backup的配置
![image](https://user-images.githubusercontent.com/107391111/212256884-06ae532d-ced6-4add-8f84-c041abb921ed.png)
4、这是我milvus监听的端口
![image](https://user-images.githubusercontent.com/107391111/212257096-2303c3ee-baac-4663-ad59-3fd8625a1aee.png)
请问如何配置呢，才能运行：./milvus-backup server

**Comment by wayblink** [comment]
hi 看起来是因为 minio的端口没有暴露出来，milvus-backup连接不上。需要修改docker-compose文件暴露minio端口

like this
```
  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
```

**Comment by citePerson** [comment]
![1673840361262](https://user-images.githubusercontent.com/107391111/212593624-1c38afdc-2268-472a-9644-9baf3c3d7b47.jpg)
服务启动完成了，但是发送接口遇到这个问题，请问是啥情况呢

**Comment by citePerson** [comment]
请求参数如图：
![image](https://user-images.githubusercontent.com/107391111/212593812-d4ebaede-862f-4c99-b0fa-5f7104443710.png)

**Comment by citePerson** [comment]
![image](https://user-images.githubusercontent.com/107391111/212598863-077868fe-c35a-4cbf-99e1-6144c475c464.png)
![image](https://user-images.githubusercontent.com/107391111/212598888-21d6554d-866e-47fd-9286-883c4ed3cfeb.png)
go main.go缺少参数，但是得readme.md中没找到，请问这里应该配置什么参数呢

**Comment by zhuwenxing** [comment]
> ![image](https://user-images.githubusercontent.com/107391111/212595292-8b85a519-ad55-4bc0-9d7e-e33e386541a5.png) 服务启动完成了，但是发送接口遇到这个问题，请问是啥情况呢

As the error log reported, the backup name format is incorrect because you can not `-` dash so you can try it with `a_bulket_backup`.

**Comment by citePerson** [comment]
> > ![image](https://user-images.githubusercontent.com/107391111/212595292-8b85a519-ad55-4bc0-9d7e-e33e386541a5.png) 服务启动完成了，但是发送接口遇到这个问题，请问是啥情况呢
> 
> As the error log reported, the backup name format is incorrect because you can not use the `-` dash so you can try it with `a_bucket_backup`.
1、这个是前端传递出错了，这个我已经改了，这是我现在最新的配置
![image](https://user-images.githubusercontent.com/107391111/212615677-8da1e76d-db0a-46ee-b4dc-79858d2e2ef8.png)
2、出错的log信息，提示我的bucket不存在和名字不合法
![image](https://user-images.githubusercontent.com/107391111/212616049-2ad31527-3cfd-43ba-a311-100b59580ea8.png)
3、下面是我宿主机路径
![image](https://user-images.githubusercontent.com/107391111/212616507-722ceb34-6128-4c81-a3b6-df4c3aea9269.png)
4、这是目前我桶数据
![image](https://user-images.githubusercontent.com/107391111/212616649-73ae8e0b-0c76-47e1-acc8-ccc9ea70d040.png)

**Comment by zhuwenxing** [comment]
It is still an invalid backup name, you should use an underscore(下划线). So the right name should be `a_bucket`
![image](https://user-images.githubusercontent.com/12268675/212622762-d52ff45d-ae8e-4ed0-912c-436b3cb36410.png)

**Comment by citePerson** [comment]
> It is still an invalid backup name, you should use an underscore(下划线). So the right name should be `a_bucket` ![image](https://user-images.githubusercontent.com/12268675/212622762-d52ff45d-ae8e-4ed0-912c-436b3cb36410.png)
但是我在minio界面创建的，_(下划线)报错，不能创建，还有其他问题呢？能帮忙解答一下么

**Comment by zhuwenxing** [comment]
It is not about the bucket name.
![image](https://user-images.githubusercontent.com/12268675/212628901-496f8f89-9d42-4d71-b6bb-329659946fe6.png)
The backup name you passed into the payload of create API is not right!

The backup name is not the same concept as the bucket name.

**Comment by citePerson** [comment]
> It is not about the bucket name. ![image](https://user-images.githubusercontent.com/12268675/212628901-496f8f89-9d42-4d71-b6bb-329659946fe6.png) The backup name you passed into the payload of create API is not right!
> 
> The backup name is not the same concept as the bucket name.

![image](https://user-images.githubusercontent.com/107391111/212631097-15904ec0-18b1-47e6-9cd2-d60dab932e9b.png)
minio里面建不了啊，失败的

**Comment by zhuwenxing** [comment]
![image](https://user-images.githubusercontent.com/12268675/212634563-17d0980a-6fdc-452b-be0a-f2e0fb404b79.png)
The value of **backup_name** in the request body should use `_` (dash).  I am not asking you to create a bucket with the name use `_`.
