### ISSUE TITLE
[Enhancement]:milvus-backup连接bucket失败

### ISSUE THREAD

**Issue by citePerson** [zilliztech/milvus-backup#73]
### What would you like to be added?

我想测试milvus的高可用功能，现在是处理单机环境，没有启用集群
1、我新建的bucket
![image](https://user-images.githubusercontent.com/107391111/212256554-f9f26a29-e580-4da7-b36d-55bb57f53573.png)
2、提示我连接失败
![image](https://user-images.githubusercontent.com/107391111/212256727-2933f51d-fc99-4fdf-b39e-bf5b466c65c3.png)
3、这是我的backup的配置
![image](https://user-images.githubusercontent.com/107391111/212256884-06ae532d-ced6-4add-8f84-c041abb921ed.png)
4、这是我milvus监听的端口
![image](https://user-images.githubusercontent.com/107391111/212257096-2303c3ee-baac-4663-ad59-3fd8625a1aee.png)
请问如何配置呢，才能运行：./milvus-backup server

**Comment by wayblink** [comment]
duplicate issue
