### ISSUE TITLE
[Bug]: vectors not included in backup to minio. no vectors present on restore.

### ISSUE THREAD

**Issue by seth814** [zilliztech/milvus-backup#76]
### Current Behavior

My config

![Screenshot from 2023-01-23 13-26-16](https://user-images.githubusercontent.com/17873279/214123927-2d9596a2-8729-439a-a3eb-60d41550ac43.png)

It is possible I'm just setting this up wrong, but I'll walk through what I'm doing.
I have bucket storage setup with s3 for my k8s cluster.
The helm chart has been configured to sync with bucketName: `shf-prod-milvus`.
Here I'm inserting data into milvus. It's similar to hello_milvus in the example scripts. It puts 10,000 vectors into a collection called demo. And I have a script to list entity num after.

![Screenshot from 2023-01-23 13-34-50](https://user-images.githubusercontent.com/17873279/214125077-27454e98-e879-40eb-9283-861a57cee190.png)

Here is my s3 bucket after data has been inserted:
![Screenshot from 2023-01-23 13-32-44](https://user-images.githubusercontent.com/17873279/214125367-88312909-f7e4-4f51-ab64-5fb7c2a5f1e0.png)

I can click down into it and see that it's storing some index info and RAW_DATA.

I assume this s3 bucket mirrors the current data in my k8s cluster.
The backup should go to the minio hosted instance in k8s. So I try this...

![Screenshot from 2023-01-23 13-39-54](https://user-images.githubusercontent.com/17873279/214125742-e7c383f8-d735-49db-b749-bdf3cf624763.png)

Looking at the minio bucket I see only metadata.

![Screenshot from 2023-01-23 13-42-01](https://user-images.githubusercontent.com/17873279/214125828-94e7dc77-e407-4a4b-a8e6-9671cbe27cc7.png)

Doesn't look like any vectors are being stored. Then I attempt a recover.

![Screenshot from 2023-01-23 13-44-54](https://user-images.githubusercontent.com/17873279/214125937-7213bf83-d451-4a5c-99ec-d68e69492719.png)

No vectors in the recovered collection.

![Screenshot from 2023-01-23 13-45-23](https://user-images.githubusercontent.com/17873279/214126049-d83419f7-ceeb-48bc-b0b4-83a9c3c43810.png)

### Expected Behavior

I'm expecting some additional vector data to be stored in my minio bucket.
Is milvus supposed to access minio for the current data in k8s? or Should it be connected to s3 like I currently have in the screenshot?
Just seems like vector data isn't being accessed correctly from milvus server.

### Steps To Reproduce

```markdown
The example at the bottom of your readme. I've tried those steps as well. Same issue. I've never gotten data to successfully restore.
```

### Environment

```markdown
Kubernetes cluster with a modified helm chart for the bucket name.
Running milvus-backup from a container built with the provided Dockerfile.
```

**Comment by zhuwenxing** [comment]
Please follow the guide in README to build a binary in local env! Using Dockerfile to build `milvus-backup` binary is still an experimental function

**Comment by wayblink** [comment]
@seth814 Hi, according to logs you provide. It seems we don't find the data of your collection 'demo' during backup, so restore nothing later.  I think there is something wrong about the path configs. Please change the log.level to `debug` in backup.yaml and offer us the new log. I will look into it.

**Comment by seth814** [comment]
Thank you. I will attempt these suggestions probably next week and get back to you.
Just don't have the time at the moment.

**Comment by seth814** [comment]
Sorry got really busy for a while.
I installed go and built the binary. Running from the local machine this time.
Did a git pull to get the latest as of the day this is posted.
Same behavior where no vectors are present in the recovery.
I have enabled debug. Here are the full logs.
Lines 1-45 is the backup. Everything after is the restore.
@wayblink 

[backup.log](https://github.com/zilliztech/milvus-backup/files/10852382/backup.log)

**Comment by teynar** [comment]
I have the exact same issue (with the release v0.2.2, building the binary as well),  could you please take a look @wayblink?

Thank you so much in advance! I am going to attach my backup log with debug level as well.

[backup.log](https://github.com/zilliztech/milvus-backup/files/11234415/backup.log)

**Comment by zhuwenxing** [comment]
@wayblink 
PTAL ~

**Comment by teynar** [comment]
> I have the exact same issue (with the release v0.2.2, building the binary as well), could you please take a look @wayblink?
> 
> Thank you so much in advance! I am going to attach my backup log with debug level as well.
> 
> [backup.log](https://github.com/zilliztech/milvus-backup/files/11234415/backup.log)

My bad, in my case the backup was empty because of the differences between the versions of docker compose and k8s, I had to properly change `bucketName` and `rootPath` as stated in the README.md. In k8s it did not find the bucket named "a-bucket" so it didn't export anything.
