### ISSUE TITLE
[Bug]: Create index hang for the collection that recovered

### ISSUE THREAD

**Issue by zhuwenxing** [zilliztech/milvus-backup#79]
### Current Behavior

```
❯ python example/verify_data.py

=== start connecting to Milvus     ===

Does collection hello_milvus_recover exist in Milvus: True
Number of entities in Milvus: hello_milvus_recover : 3000

=== Start Creating index IVF_FLAT  ===
```
The output stuck at this step.

[standalone.log](https://github.com/zilliztech/milvus-backup/files/10575419/standalone.log)

**Comment by zhuwenxing** [comment]
It seems that the Milvus backup tool is not compatible with Milvus mater-latest image `master-20230203-dfa2dac8`.
I test it with v2.2.2, and it works well.

**Comment by wayblink** [comment]
will fix in https://github.com/milvus-io/milvus/pull/21980
