### ISSUE TITLE
[Bug]: There is a certain probability that the test case will get stuck

### ISSUE THREAD

**Issue by zhuwenxing** [zilliztech/milvus-backup#83]
### Current Behavior

![image](https://user-images.githubusercontent.com/12268675/216918354-c63caa51-0453-4093-804f-b9d055a3341e.png)

A test case flush needs about 900s
![image](https://user-images.githubusercontent.com/12268675/216919889-cc77969b-829a-4374-9dc7-459ace06e6e2.png)

### Expected Behavior

all test cases should be finished in 10min

### Anything else?

failed run: https://github.com/zilliztech/milvus-backup/actions/runs/4101231745/jobs/7072812476
log:
[logs-docker-compose-cluster](https://github.com/zilliztech/milvus-backup/suites/10796469555/artifacts/542947662)

**Comment by wayblink** [comment]
only happen once. Close it temporally
